version: '3.9'
services:
  wrk0:
    build: ./miner
    environment:
      - NH_REGION=${NH_REGION}
      - ALGO=${ALGO}
      - BTC_ADDR=${BTC_ADDR}
      - WORKER_NAME=${container_name}
      - THREAD=${THREAD}
    restart: always
