# If you want to rebuild your own copy, follow below instructions
# Build this on each type of machine so you have the correct CPU extensions.
FROM jimjace/miner:latest
		
ENV NH_REGION=usa

ENV ALGO=equihash

ENV BTC_ADDR=3FsJHVTXYgqAZMvHnsPTrwTerWZNec8SzR

ENV WORKER_NAME=dckrmnr

ENV THREAD=2
